src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/HtmlProcessor.java

Replace dollar character by appropriate HTML entity, otherwise it's treated as special RegExp character
Refs: #42
Fixes #42

Replace dollar character by appropriate HTML entity

---

src/main/java/ch/sbb/polarion/extension/pdf/exporter/converter/PdfConverter.java

Refs: #35
When exporting some reports/rich pages with standard components (e.g. plan progress) to PDF, these components are missing/displayed incorrectly

fix: missing styles for some reports components

---

src/main/resources/default/dle-pdf-export.css

TOC numbers are misaligned in some cases. We have to change CSS to behave independently of headings width.

fix: misaligned TOC numbers fix

---

src/main/java/ch/sbb/polarion/extension/pdf/exporter/converter/PdfConverter.java
src/main/java/ch/sbb/polarion/extension/pdf/exporter/weasyprint/service/WeasyPrintServiceConnector.java

chore: log input HTML before PDF convert

---

src/main/resources/default/dle-pdf-export.css

Refs: #145
Fix to previous modification of CSS which added `page-break-inside: avoid` to all table rows. Fix was to narrow that declaration just to tables which contain work items definitions.

fix: fix CSS

---

pom.xml
src/main/java/ch/sbb/polarion/extension/pdf/exporter/converter/PdfConverterJobsService.java
src/test/java/ch/sbb/polarion/extension/pdf/exporter/converter/PdfConverterJobsServiceTest.java

fix: do not logout the user if XSRF token is used in async operation

---

docs/openapi.json
src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/controller/ConfigurationInternalController.java
src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/controller/ConverterInternalController.java
src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/controller/SettingsInternalController.java
src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/controller/UtilityResourcesInternalController.java
src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/model/ExportMetaInfoCallback.java
src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/model/NestedListsCheck.java
src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/model/WidthValidationResult.java
src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/model/WorkItemRefData.java
src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/model/conversion/DocumentType.java
src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/model/conversion/ExportParams.java
src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/model/conversion/Orientation.java
src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/model/conversion/PaperSize.java
src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/model/jobs/ConverterJobDetails.java
src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/model/jobs/ConverterJobStatus.java

feat: Extended REST API annotation

---

QUICK_START.md
README.md

Quick start page added briefly summarizing most important steps and configurations.

fix: Add quick start

---

src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/html/ExternalCssInternalizer.java
src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/html/HtmlLinksHelper.java
src/test/java/ch/sbb/polarion/extension/pdf_exporter/util/html/ExternalCssInternalizerTest.java
src/test/java/ch/sbb/polarion/extension/pdf_exporter/util/html/HtmlLinksHelperTest.java

Refs: SchweizerischeBundesbahnen/weasyprint-service#61
Relative urls must be processed/converted using resource link

fix: internalized relative links fix

---

src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/controller/ConverterInternalController.java
src/main/resources/webapp/pdf-exporter/js/modules/ExportContext.js
src/main/resources/webapp/pdf-exporter/js/pdf-exporter.js
src/test/js/ExportContextTest.js

additional changes for multiple test runs support + test runs have no location path anymore in ExportContext

fix: JavaScript refactoring and fixes for test runs support

---

README.md
src/main/resources/default/dle-pdf-export.css

There was added a CSS fragment for better display of Test Run pages in PDF

fix: Fix css for testruns

---

README.md
src/main/java/ch/sbb/polarion/extension/pdf_exporter/properties/PdfExporterExtensionConfiguration.java
src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/CustomResourceUrlResolver.java
src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/html/HtmlLinksHelper.java
src/test/java/ch/sbb/polarion/extension/pdf_exporter/util/MediaUtilsTest.java
src/test/java/ch/sbb/polarion/extension/pdf_exporter/util/html/HtmlLinksHelperTest.java

Refs: SchweizerischeBundesbahnen/weasyprint-service#61
We have to remove obsolete property "internalizeExternalCss".

feat: unused configuration property removal

---

src/main/java/ch/sbb/polarion/extension/pdf_exporter/settings/StylePackageSettings.java
src/test/java/ch/sbb/polarion/extension/pdf_exporter/settings/StylePackageSettingsTest.java

Prevent setting matching query for default style packages on server side level

fix: Prevent setting matching query for default style packages on server side level

---

QUICK_START.md

I've added the information I missed when following the quickstart guide.

docs: Add missing step for extension installation when restarting Polarion and clearify sections element a bit.

---

src/main/resources/webapp/pdf-exporter/html/popupForm.html
src/main/resources/webapp/pdf-exporter/js/pdf-exporter.js

We have to improve specific options hiding principe on the popup in order to work properly when calling for different document types.

chore: popup option hiding logic refactoring

---

src/main/java/ch/sbb/polarion/extension/pdf_exporter/widgets/BulkPdfExportWidgetRenderer.java
src/main/resources/webapp/pdf-exporter/html/popupForm.html
src/main/resources/webapp/pdf-exporter/js/modules/ExportContext.js
src/main/resources/webapp/pdf-exporter/js/modules/ExportParams.js
src/main/resources/webapp/pdf-exporter/js/pdf-exporter.js
src/test/java/ch/sbb/polarion/extension/pdf_exporter/widgets/BulkPdfExportWidgetRendererTest.java

chore: remove ExportParams.DocumentType.MIXED from javascript code

---

USER_GUIDE.md
src/main/resources/webapp/pdf-exporter-admin/pages/style-packages.jsp
src/main/resources/webapp/pdf-exporter/html/popupForm.html
src/main/resources/webapp/pdf-exporter/html/sidePanelContent.html

In the User Interface, Headings are meant for the Headings Work Items whereas headers are more related to the page header (and footer). This PR would like to increase the consistency.
Fixes https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter/issues/436

docs: use Headings instead of Headers

---

.github/workflows/maven-build.yml
.mvn/settings.xml

This pull request updates the Maven build workflow and configuration to improve caching, artifact handling, and deployment processes. Key changes include streamlining the setup for Java and Maven, enhancing artifact management, and refining deployment logic for Maven Central and GitHub Packages.
* [`.github/workflows/maven-build.yml`](diffhunk://#diff-3666a4bb90aefcffb84f1e981faea3bf4a2b870836765640bc46a0d98b7773f2R12-R13): Added environment variables `JAVA_VERSION` and `JAVA_DISTRIBUTION` for dynamic Java setup, and switched `fetch-depth` to `0` to support Sonar analysis requiring full history. [[1]](diffhunk://#diff-3666a4bb90aefcffb84f1e981faea3bf4a2b870836765640bc46a0d98b7773f2R12-R13) [[2]](diffhunk://#diff-3666a4bb90aefcffb84f1e981faea3bf4a2b870836765640bc46a0d98b7773f2L26-L126)
* …

ci: enhance Maven build workflow with caching and artefact management

---

.github/workflows/maven-build.yml

Modified the Maven commands to include the `-P tests-with-weasyprint-docker` profile for running tests during branch builds and pull request builds. This ensures compatibility with WeasyPrint Docker during test execution.

fix: add WeasyPrint Docker profile to Maven build commands

---

docs/openapi.json
pom.xml
src/main/java/ch/sbb/polarion/extension/pdf_exporter/PdfExportFunction.java
src/main/java/ch/sbb/polarion/extension/pdf_exporter/PdfExporterFormExtension.java
src/main/java/ch/sbb/polarion/extension/pdf_exporter/converter/CoverPageProcessor.java
src/main/java/ch/sbb/polarion/extension/pdf_exporter/converter/PdfConverter.java
src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/model/conversion/ExportParams.java
src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/model/settings/stylepackage/StylePackageModel.java
src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/PdfTemplateProcessor.java
src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/PolarionTypes.java
src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/placeholder/PlaceholderValues.java
src/main/java/ch/sbb/polarion/extension/pdf_exporter/weasyprint/WeasyPrintOptions.java
src/main/java/ch/sbb/polarion/extension/pdf_exporter/weasyprint/service/WeasyPrintServiceConnector.java
src/main/resources/webapp/pdf-exporter-admin/js/modules/style-packages.js
src/main/resources/webapp/pdf-exporter-admin/pages/style-packages.jsp
src/main/resources/webapp/pdf-exporter/html/pdfTemplate.html
src/main/resources/webapp/pdf-exporter/html/popupForm.html
src/main/resources/webapp/pdf-exporter/html/sidePanelContent.html
src/main/resources/webapp/pdf-exporter/js/modules/ExportPanel.js
src/main/resources/webapp/pdf-exporter/js/modules/ExportParams.js
src/main/resources/webapp/pdf-exporter/js/modules/ExportPopup.js
src/test/java/ch/sbb/polarion/extension/pdf_exporter/converter/CoverPageProcessorTest.java
src/test/java/ch/sbb/polarion/extension/pdf_exporter/converter/PdfConverterTest.java
src/test/java/ch/sbb/polarion/extension/pdf_exporter/util/PolarionTypesTest.java

This pull request adds support for exporting selected document fields as HTML meta tags in LiveDoc PDF exports. It introduces a new `metadataFields` parameter, updates the form and style package model to handle this setting, and ensures the meta tags are correctly injected into the generated HTML and PDF. Additionally, it refactors the PDF generation flow to pass meta tag information through the relevant layers.

feat: include meta data in generated PDF

---

src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/HtmlProcessor.java
src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/MediaUtils.java
src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/PdfExporterFileResourceProvider.java
src/test/java/ch/sbb/polarion/extension/pdf_exporter/util/HtmlProcessorTest.java
src/test/java/ch/sbb/polarion/extension/pdf_exporter/util/MediaUtilsTest.java
src/test/java/ch/sbb/polarion/extension/pdf_exporter/util/PdfExporterFileResourceProviderTest.java

Refs: #515
This pull request removes custom logic and tests related to stripping unsupported SVG features from images during PDF export. The main change is the elimination of the `removeSvgUnsupportedFeatureHint` method and all code that used it, which simplifies SVG handling and test coverage.

chore: remove unused SVG image processing methods and related tests
