- .github/workflows/maven-release.yml
- .scripts/convert-readme.sh
maven build will not fail on local machines, but will fail during GitHub Actions build
> fix: check if required commands are available

- src/test/java/ch/sbb/polarion/extension/pdf/exporter/converter/PdfConverterJobsServiceTest.java
> fix: Fixed unstable JobsService test

- .github/workflows/maven-release.yml
> ci: updated to support deployment to maven central

- pom.xml
> ci: pom.xml extended with required info

- .github/workflows/pr.yml
- LICENSES/SBB.txt
> chore: update with template

- src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/exception/NoSuchElementExceptionMapper.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/exception/UnresolvableObjectExceptionMapper.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/exception/WrapperExceptionMapper.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/exception/XLIFFExceptionMapper.java
- src/main/resources/webapp/pdf-exporter/js/export-pdf.js
- src/main/resources/webapp/pdf-exporter/js/pdf-exporter.js
#33 
- [] If applicable, I have added tests that prove my fix is effective or that my feature works
> fix: Fixed exception handling.

- src/main/resources/webapp/pdf-exporter/js/export-pdf.js
> fix: Fixed check nested lists.

- CHANGELOG.md
- pom.xml
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/converter/HtmlToPdfConverter.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/model/WorkItemRefData.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/settings/CoverPageSettings.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/HtmlProcessor.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/LiveDocCommentsProcessor.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/MediaUtils.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/configuration/ConfigurationStatusUtils.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/html/HtmlLinksHelper.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/placeholder/PlaceholderProcessor.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/regex/IRegexEngine.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/regex/RegexEngineJavaUtilImpl.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/regex/RegexEngineRE2JImpl.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/regex/RegexMatcher.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/weasyprint/cli/WeasyPrintExecutor.java
- src/main/resources/webapp/pdf-exporter/js/export-pdf.js
- src/test/java/ch/sbb/polarion/extension/pdf/exporter/util/HtmlProcessorTest.java
- src/test/java/ch/sbb/polarion/extension/pdf/exporter/util/regex/RegexMatcherTest.java
> feat: Export of other languages configured for LiveDoc

- src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/model/conversion/ExportParams.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/LiveDocHelper.java
- src/main/resources/webapp/pdf-exporter/js/export-pdf.js
- src/main/resources/webapp/pdf-exporter/js/pdf-exporter.js
> feat: portal language for LiveDoc is supported for PDF export

- src/main/resources/webapp/pdf-exporter/js/pdf-exporter.js
> fix: Fixed export of a live document from a collection

- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/HtmlProcessor.java
- src/main/resources/default/cover-page/English/template.html
- src/main/resources/default/cover-page/German/template.html
- src/main/resources/default/dle-pdf-export.css
- src/main/resources/default/wiki.css
- src/main/resources/webapp/pdf-exporter-admin/pages/cover-page.jsp
- src/main/resources/webapp/pdf-exporter-admin/pages/css.jsp
- src/main/resources/webapp/pdf-exporter-admin/pages/filename-template.jsp
- src/main/resources/webapp/pdf-exporter-admin/pages/header-footer.jsp
- src/main/resources/webapp/pdf-exporter-admin/pages/localization.jsp
- src/main/resources/webapp/pdf-exporter-admin/pages/style-packages.jsp
- src/main/resources/webapp/pdf-exporter/html/popupForm.html
- src/main/resources/webapp/pdf-exporter/html/sidePanelContent.html
- src/main/resources/webapp/pdf-exporter/js/export-pdf.js
- src/main/resources/webapp/pdf-exporter/js/pdf-exporter.js
- src/main/resources/webapp/pdf-exporter/js/starter.js
- src/test/java/ch/sbb/polarion/extension/pdf/exporter/converter/PdfConverterTest.java
- src/test/java/ch/sbb/polarion/extension/pdf/exporter/util/HtmlProcessorTest.java
- src/test/java/ch/sbb/polarion/extension/pdf/exporter/weasyprint/BaseWeasyPrintTest.java
- src/test/java/ch/sbb/polarion/extension/pdf/exporter/weasyprint/exporter/FileWaitStrategy.java
> chore: reliability sonar fix

- src/main/resources/webapp/pdf-exporter-admin/pages/about.jsp
> fix: configuration status is available again

- src/main/resources/default/wiki.css
- src/main/resources/webapp/pdf-exporter-admin/pages/localization.jsp
- src/main/resources/webapp/pdf-exporter/js/export-pdf.js
- src/main/resources/webapp/pdf-exporter/js/pdf-exporter.js
Sonarqube security & maintainability issues fixes
> chore: sonarqube security & maintainability issues fixes

- README.md
> chore: <POLARION_HOME>/etc/polarion.properties -> polarion.properties

- src/main/java/ch/sbb/polarion/extension/pdf/exporter/converter/PdfConverter.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/HtmlProcessor.java
- src/test/java/ch/sbb/polarion/extension/pdf/exporter/converter/PdfConverterTest.java
- src/test/java/ch/sbb/polarion/extension/pdf/exporter/util/HtmlProcessorTest.java
to fix resolving of possible non-accessible host from weasyprint service
Refs: #112
> feat: embed all the images in header/footer as base64 data

- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/configuration/ConfigurationStatusUtils.java
> chore: info about the used weasyprint docker-image version

- docs/openapi.json
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/converter/PdfConverter.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/controller/ConverterApiController.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/controller/ConverterInternalController.java
> feat: REST API for getting prepared HTML content for WeasyPrint

- .pre-commit-config.yaml
- docs/openapi.json
> build: JSON sorter in pre-commit

- src/main/resources/webapp/pdf-exporter/js/starter.js
> fix: Export to PDF button on LiveReport page works as expected again

- docs/openapi.json
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/converter/PdfConverter.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/model/conversion/ExportParams.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/DocumentFileNameHelper.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/LiveDocHelper.java
- src/main/resources/webapp/pdf-exporter/js/export-pdf.js
- src/main/resources/webapp/pdf-exporter/js/pdf-exporter.js
- src/test/java/ch/sbb/polarion/extension/pdf/exporter/converter/PdfConverterTest.java
- src/test/java/ch/sbb/polarion/extension/pdf/exporter/weasyprint/PdfConverterWeasyPrintTest.java
> fix: LiveReport Page now respects URL Parameters

- README.md
- src/main/resources/webapp/pdf-exporter-admin/js/webhooks.js
- src/main/resources/webapp/pdf-exporter-admin/pages/webhooks.jsp
Refs: #91
Webhooks documentation extended
> docs: Webhooks documentation extended

- src/main/resources/webapp/pdf-exporter/js/pdf-exporter.js
> chore: CodeQL warning fix

- docs/openapi.json
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/converter/PdfConverter.java
- src/main/resources/webapp/pdf-exporter/js/pdf-exporter.js
- src/test/java/ch/sbb/polarion/extension/pdf/exporter/converter/PdfConverterTest.java
> fix: Feature/fix cover page

- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/LiveDocHelper.java
> fix: Fixed getting project baseline

- README.md
> chore: move Asynchronous PDF Export section to Advanced configuration

- pom.xml
> fix: link on About page work as expected

- .github/workflows/maven-build.yml
adjusted github actions workflow according to the latest agreement
> ci: github actions workflow adjusted

- .github/workflows/maven-build.yml
> ci: fix upload assets

- src/main/resources/webapp/pdf-exporter-admin/js/style-packages.js
> fix: style packages can be saved without webhooks

- README.md
- docs/openapi.json
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/PdfExporterFormExtension.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/converter/PdfConverter.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/controller/UtilityResourcesApiController.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/controller/UtilityResourcesInternalController.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/model/conversion/DocumentType.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/model/settings/filename/FileNameTemplateModel.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/rest/model/settings/stylepackage/StylePackageModel.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/settings/FileNameTemplateSettings.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/DocumentFileNameHelper.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/HtmlProcessor.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/LiveDocHelper.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/util/velocity/VelocityEvaluator.java
- src/main/java/ch/sbb/polarion/extension/pdf/exporter/widgets/ExportToPdfButtonRenderer.java
- src/main/resources/webapp/pdf-exporter-admin/js/filename-template.js
- src/main/resources/webapp/pdf-exporter-admin/pages/filename-template.jsp
- src/main/resources/webapp/pdf-exporter/js/pdf-exporter.js
- src/test/java/ch/sbb/polarion/extension/pdf/exporter/settings/FileNameTemplateSettingsTest.java
Refs:  #192 
we would like to export test runs as pdf
breaking change because of changing `export-filename` endpoint
> feat!: add support of test runs

- pom.xml
- src/main/resources/webapp/pdf-exporter/js/modules/ExportContext.js
disable all tests using one option
> fix: skipping JavaScript tests if -DskipTests is used

- src/main/resources/default/dle-pdf-export.css
Refs: #192
Fix CSS for testruns
> fix: fix CSS for testruns

- src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/HtmlProcessor.java
- src/main/resources/webapp/pdf-exporter/js/modules/ExportContext.js
- src/main/resources/webapp/pdf-exporter/js/pdf-exporter.js
Fix export testruns from listview
> fix: export of TestRun not working from "list view"

- src/main/resources/webapp/pdf-exporter/js/starter.js
Fix style of button in toolbar
Add right margin not to overlap scrollbar
> fix: Fix style of button in toolbar

- src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/configuration/WeasyPrintStatusProvider.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/weasyprint/service/model/WeasyPrintInfo.java
> feat: display weasyprint server build timestamp and chromium version in extension info table

- docs/openapi.json
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/model/conversion/ExportParams.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/DocumentDataHelper.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/configuration/DleToolbarStatusProvider.java
> fix: fix renamed properties in schema

- src/main/resources/webapp/pdf-exporter/js/side-panel-starter.js
Fix loading JS module
Load JS module proper way
> fix: Fix loading JS module

- docs/openapi.json
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/PdfExporterFileResourceProvider.java
> fix: do not remove GenericUrlResolver from PolarionUrlResolver singleton

- src/main/java/ch/sbb/polarion/extension/pdf_exporter/PdfExporterFormExtension.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/model/settings/stylepackage/StylePackageModel.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/service/PdfExporterPolarionService.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/settings/StylePackageSettings.java
- src/main/resources/webapp/pdf-exporter-admin/js/style-packages.js
- src/main/resources/webapp/pdf-exporter-admin/pages/style-packages.jsp
- src/main/resources/webapp/pdf-exporter/js/pdf-exporter.js
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/settings/StylePackageSettingsTest.java
Add the ability to sort style packages using weights.
> feat: style packages weights

- pom.xml
> fix: set configuration properties prefix

- src/main/java/ch/sbb/polarion/extension/pdf_exporter/properties/PdfExporterExtensionConfiguration.java
> fix: use "pdf/a-2b" as default value for "weasyprint.pdf.variant" config property

- src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/controller/SettingsApiController.java
Refs: #254
New weight-related REST endpoints don't work properly. We have to fix them.
> fix: REST endpoints for getting/updating weights aren't available

- src/main/resources/META-INF/MANIFEST.MF
> fix: MANIFEST.MF contains org.apache.tika.patched for 2404 and org.apache.tika for 2310

- pom.xml
implemented in generic in about page
Refs: #257
> feat: display non-valid/obsolete configuration properties

- README.md
- pom.xml
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/properties/PdfExporterExtensionConfiguration.java
> feat: "default" and "description" columns added to extension configuration properties

- .github/workflows/maven-build.yml
- .github/workflows/pr.yml
- .github/workflows/release-please.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- QUICK_START.md
- pom.xml
> chore: setup sonarcloud

- renovate.json
Add Renovate for versions.properties
> ci: add renovate for versions.properties

- src/main/java/ch/sbb/polarion/extension/pdf_exporter/converter/PdfConverter.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/service/PdfExporterPolarionService.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/widgets/BulkPdfExportWidget.java
> fix: SonarQube code smells

- README.md
Add sonar badges for better visualisation 
> chore: add sonar badges

- src/main/resources/webapp/pdf-exporter/js/pdf-exporter.js
Fixes #271
Fix JS - null pointer errors and absent parameter with later decomposing
> fix: Fix JS - null pointer errors and absent parameter with later decomposing

- docs/openapi.json
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/controller/ConverterInternalController.java
Refs: #281
Added missing OpenAPI annotations
> fix: Fixed OpenAPI specification

- pom.xml
Refs: #272
implemented in generic for all extensions
> fix: SonarCloud badges removed from about page

- pom.xml
> feat: Polarion 2410 support

- docs/openapi.json
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/PdfExporterRestApplication.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/controller/TestRunAttachmentsApiController.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/controller/TestRunAttachmentsInternalController.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/model/attachments/TestRunAttachment.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/model/conversion/ExportParams.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/model/settings/stylepackage/StylePackageModel.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/service/PdfExporterPolarionService.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/WildcardUtils.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/placeholder/PlaceholderProcessor.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/widgets/BulkPdfExportWidgetRenderer.java
- src/main/resources/webapp/pdf-exporter-admin/js/style-packages.js
- src/main/resources/webapp/pdf-exporter-admin/pages/style-packages.jsp
- src/main/resources/webapp/pdf-exporter/html/popupForm.html
- src/main/resources/webapp/pdf-exporter/js/bulk-pdf-exporter.js
- src/main/resources/webapp/pdf-exporter/js/export-common.js
- src/main/resources/webapp/pdf-exporter/js/export-pdf.js
- src/main/resources/webapp/pdf-exporter/js/modules/ExportParams.js
- src/main/resources/webapp/pdf-exporter/js/pdf-exporter.js
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/service/PdfExporterPolarionServiceTest.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/util/WildcardUtilsTest.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/util/placeholder/PlaceholderProcessorTest.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/weasyprint/PdfConverterWeasyPrintTest.java
> feat: export pdf attachments in addition

- src/main/resources/webapp/pdf-exporter/js/modules/ExportContext.js
- src/test/js/ExportContextTest.js
Refs: #303
fix context regexp and added additional JS tests
> fix: error loading of document export popup dialog when document is opened in collection

- src/main/java/ch/sbb/polarion/extension/pdf_exporter/PdfExporterFormExtension.java
- src/main/resources/webapp/pdf-exporter/js/export-pdf.js
- src/main/resources/webapp/pdf-exporter/js/modules/ExportContext.js
- src/test/js/ExportContextTest.js
baseline view is now supported
> feat: support baseline view

- README.md
Refs: #299
refuse support of previous version of Polarion
> feat!: support only Polarion 2410

- .github/workflows/maven-build.yml
> ci: workflow update

- README.md
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/PdfExportFunction.java
- src/main/resources/META-INF/hivemodule.xml
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/PdfExportFunctionTest.java
Refs: #291
User can define a workflow function that exports a PDF file and attaches it to a newly created or already existing work item.
> feat: export of LiveDoc as Workflow Function

- src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/velocity/VelocityEvaluator.java
Refs: #344
use RichPageScriptRenderer for Velocity evaluation 
> feat: evaluate velocity using RichPageScriptRenderer

- src/main/java/ch/sbb/polarion/extension/pdf_exporter/converter/CoverPageProcessor.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/converter/PdfConverter.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/converter/CoverPageProcessorTest.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/weasyprint/PdfConverterWeasyPrintTest.java
Fixes #356
Embed images as base64 data into cover page
> fix: Embed images as base64 data into cover page

- src/main/resources/webapp/pdf-exporter-admin/pages/webhooks.jsp
Get rid of unneeded property value on UI
> chore: Get rid of unneeded property value on UI

- src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/controller/ConverterInternalController.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/model/settings/stylepackage/DocIdentifier.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/configuration/DleToolbarStatusProvider.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/configuration/LiveReportMainHeadStatusProvider.java
- src/main/resources/webapp/pdf-exporter/js/modules/ExportContext.js
- src/main/resources/webapp/pdf-exporter/js/pdf-exporter.js
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/util/configuration/DleToolbarStatusProviderTest.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/util/configuration/LiveReportMainHeadStatusProviderTest.java
- src/test/js/ExportContextTest.js
> fix: export of testruns

- src/main/java/ch/sbb/polarion/extension/pdf_exporter/converter/CoverPageProcessor.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/MediaUtils.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/placeholder/PlaceholderProcessor.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/placeholder/PlaceholderValues.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/converter/CoverPageProcessorTest.java
> fix: support {{ PAGE_NUMBER }} and {{ PAGES_TOTAL_COUNT }} on cover page

- src/main/resources/webapp/pdf-exporter/js/modules/ExportPopup.js
Constructor param in ExportPopup declared incorrectly.
> chore: proper constructor default param declaration

- src/main/resources/webapp/pdf-exporter-admin/js/modules/css.js
> fix: Fix storing custom CSS

- README.md
- docs/openapi.json
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/LiveDocTOCGenerator.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/util/LiveDocTOCGeneratorTest.java
- src/test/resources/tableOfContentLiveDocWikiContentAfterProcessing.html
- src/test/resources/tableOfContentLiveDocWikiContentBeforeProcessingFormatted.html
Refs: #415
support ToC for wiki content added
> fix: wiki content toc support

- src/test/java/ch/sbb/polarion/extension/pdf_exporter/util/MediaUtilsTest.java
We have to remove all guava lib usage.
> chore: guava usage removal

- .github/workflows/maven-build.yml
it will allow better collaboration. Still repo maintainers must approve the run for the action 
> ci: allow run workflows for prs from forks

- src/main/java/ch/sbb/polarion/extension/pdf_exporter/PdfExportFunction.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/PdfExportFunctionTest.java
trying to fix sporadical failure of tests in github workflows
> fix: trying to make tests more stable

- USER_GUIDE.md
Refs: https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter/issues/428
Correct grammatical errors and wrong image references in `USER_GUIDE.md`.
> docs: address editorial issues in USER_GUIDE.md

- docs/openapi.json
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/model/conversion/ExportParams.java
We have to remove deprecated param.
> chore!: remove deprecated enableCommentsRendering param

- USER_GUIDE.md
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/PdfTemplateProcessor.java
- src/main/resources/default/dle-pdf-export.css
- src/main/resources/webapp/pdf-exporter/html/pdfTemplate.html
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/util/PdfTemplateProcessorTest.java
Fixes #461
Watermark should be configurable by project's admin
> feat: Configurable watermark

- src/main/java/ch/sbb/polarion/extension/pdf_exporter/service/PdfExporterPolarionService.java
- src/main/resources/webapp/pdf-exporter/js/modules/ExportBulk.js
> fix: fixed loading of test runs

- docs/openapi.json
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/converter/CoverPageProcessor.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/converter/PdfConverter.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/model/conversion/ExportParams.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/model/documents/DocumentData.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/model/documents/UniqueObjectConverter.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/model/documents/adapters/CommonUniqueObjectAdapter.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/model/documents/adapters/IUniqueObjectAdapter.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/model/documents/adapters/TestRunAdapter.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/rest/model/settings/stylepackage/StylePackageModel.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/weasyprint/WeasyPrintConverter.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/weasyprint/service/WeasyPrintServiceConnector.java
- src/main/resources/webapp/pdf-exporter-admin/js/modules/style-packages.js
- src/main/resources/webapp/pdf-exporter-admin/pages/style-packages.jsp
- src/main/resources/webapp/pdf-exporter/html/popupForm.html
- src/main/resources/webapp/pdf-exporter/js/modules/ExportBulk.js
- src/main/resources/webapp/pdf-exporter/js/modules/ExportParams.js
- src/main/resources/webapp/pdf-exporter/js/modules/ExportPopup.js
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/converter/CoverPageProcessorTest.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/converter/PdfConverterTest.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/rest/model/documents/DocumentDataTest.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/weasyprint/PdfConverterWeasyPrintTest.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/weasyprint/base/BaseWeasyPrintTest.java
Fixes #497
Include attachments into PDF by request
> feat: Include attachments into PDF

- src/main/resources/webapp/pdf-exporter/js/modules/ExportPanel.js
> fix: fixed page width validation

- src/main/java/ch/sbb/polarion/extension/pdf_exporter/widgets/BulkPdfExportWidget.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/converter/PdfConverterJobsServiceTest.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/rest/controller/ConverterApiControllerTest.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/settings/CoverPageSettingsTest.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/settings/FileNameTemplateSettingsTest.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/settings/HeaderFooterSettingsTest.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/settings/StylePackageSettingsTest.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/util/placeholder/PlaceholderProcessorTest.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/weasyprint/PdfConverterWeasyPrintTest.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/weasyprint/PdfConverterWeasyPrintWatermarkTest.java
- src/test/java/ch/sbb/polarion/extension/pdf_exporter/weasyprint/base/BasePdfConverterTest.java
improve integration tests and fix code smells from SonarQube
> refactor: improve integration tests and fix code smells from SonarQube

- package-lock.json
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/constants/CssProp.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/adjuster/ImageSizeAdjuster.java
- src/main/java/ch/sbb/polarion/extension/pdf_exporter/util/adjuster/ImageSizeInTablesAdjuster.java
- src/test/resources/cutLocalUrlsWithRolesFilteringAfterProcessing.html
- src/test/resources/fitImagesWidthAfterProcessing.html
- src/test/resources/fitToLandscapePageAfterProcessing.html
- src/test/resources/fitToPortraitPageAfterProcessing.html
- src/test/resources/linkedWorkItemsAfterProcessing.html
- src/test/resources/linkedWorkItemsTableAfterProcessing.html
> fix: Fixes max height of images
